### ISSUE TITLE
Configure sm DA to deploy iam engine

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-retrieval-augmented-generation#12]

**Comment by ocofaigh** [comment]
This is already done. See https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/releases/tag/v1.6.0

**Comment by ocofaigh** [comment]
Sorry my bad, I guess this is tracking enabling it in the RAG stack, so re-opening

**Comment by ocofaigh** [comment]
I'm going to close this issue because the RAG stack is being updated to consume the genai stack, and the genai stack consumes the core security services stack (which will have the ability to enable the engine after https://github.com/terraform-ibm-modules/stack-ibm-core-security-services/pull/70 is merged). Updating of RAG stack to consume genai stack is being tracked here https://github.ibm.com/goldeneye/issues/issues/9896
