### ISSUE TITLE
Configure SCC to create default attachment aligned with compliance claims for this stack

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-retrieval-augmented-generation#13]

**Comment by ocofaigh** [comment]
Coming in https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/pull/180

**Comment by ocofaigh** [comment]
PR merged. The current code now creates an SCC attachment by default, however its scoped to the full account and the schedule is also hard coded. Since Jordan is off for a few weeks, I created https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/188 to track adding these updates, and going to close this issue.
