### ISSUE TITLE
Prefix is not passed to SCC DA

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/stack-retrieval-augmented-generation#130]
Prefix value from the stack input needs to be passed to the SCC DA

https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/blob/f12b0268ecb7c4ad05dbdbe49e65e21dd86cded5/stack_definition.json#L192

**Comment by ocofaigh** [comment]
I'm going to close this issue because the RAG stack is being updated to consume the genai stack, and the genai stack consumes the core security services stack (which has the fix for prefix in it). Updating of RAG stack to consume genai stack is being tracked here https://github.ibm.com/goldeneye/issues/issues/9896
